// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: camera

#include "ui.h"

void openCamera(lv_event_t * e)
{
	// Your code here
}

void tunrOnLED(lv_event_t * e)
{
	// Your code here
}

void turnOffLED(lv_event_t * e)
{
	// Your code here
}

void change_blue(lv_event_t * e)
{
	// Your code here
}

void change_red(lv_event_t * e)
{
	// Your code here
}

void change_green(lv_event_t * e)
{
	// Your code here
}

void closeCamera(lv_event_t * e)
{
	// Your code here
}

void take_picture(lv_event_t * e)
{
	// Your code here
}
