// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: camera

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void openCamera(lv_event_t * e);
void tunrOnLED(lv_event_t * e);
void turnOffLED(lv_event_t * e);
void change_blue(lv_event_t * e);
void change_red(lv_event_t * e);
void change_green(lv_event_t * e);
void closeCamera(lv_event_t * e);
void take_picture(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
