// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11/Users/myry/Documents/Github/3.5inch-camera-controller/01.Software/03_FreeRTOS/ui_events.h
// Project name: flash

#include "ui.h"
extern int temp;

void flash(lv_event_t* e) {
  if (temp == 1) {
    temp = 0;
  } else if (temp == 0) {
    temp = 1;
  }
}
