// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0/Users/myry/Documents/Github/3.5inch-camera-controller/01.Software/03_FreeRTOS/ui_helpers.c
// LVGL version: 8.3.11
// Project name: flash

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void flash(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
