// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: flash

#include "ui.h"

void flash(lv_event_t* e) {
  if (digitalRead(4) == 0) {
    digitalWrite(4, 1);
  } else {
    digitalWrite(4, 0);
  }
}
