// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: camera

#include "ui.h"

extern int led_state, camera_state;

void openCamera(lv_event_t * e)
{
	camera_state = 1;
}

void tunrOnLED(lv_event_t * e)
{
	led_state = 1;
}

void turnOffLED(lv_event_t * e)
{
	led_state = 0;
}

void change_clolor(lv_event_t * e)
{
	int value = 0;
  value = lv_slider_get_value(ui_Slider1);//ui_Slider1 ui.h文件

}

void closeCamera(lv_event_t * e)
{
	camera_state = 0;
}
