// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: camera

#include "ui.h"
extern int camera_state;
extern int led_state;

void openCamera(lv_event_t* e) {
  camera_state = 1;
}

void tunrOnLED(lv_event_t* e) {
  led_state = 1;
}

void turnOffLED(lv_event_t* e) {
  led_state = 0;
}

void change_clolor(lv_event_t* e) {
  // Your code here
}

void closeCamera(lv_event_t* e) {
  camera_state = 0;
}
