// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11/Users/myry/Documents/Github/3.5inch-camera-controller/01.Software/03_FreeRTOS/ui_events.h
// Project name: flash

#include "ui.h"

void flash(lv_event_t* e) {
  if (digitalRead(4) == 0) {
    digitalWrite(4, 1);
  } else {
    digitalWrite(4, 0);
  }
}
