// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: camera

#include "ui.h"

void tunrOnLED(lv_event_t * e)
{
	// Your code here
}

void turnOffLED(lv_event_t * e)
{
	// Your code here
}

void change_clolor(lv_event_t * e)
{
	// Your code here
}
